
oauth2:
  cors:
    allow-credentials: true
    allowed-headers: "*"
    allowed-origins:
      - http://localhost:3000
      - http://localhost:8080
    max-age: 3600
    allowed-methods:
      - PUT
      - GET
      - POST
      - OPTIONS
      - DELETE
      - PATCH
  rsa:
    public-key: classpath:certs/public.pem
    private-key: classpath:certs/private.pem
  oauth2:
    authorized-redirect-uris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
  recaptcha:
    disabled: true
    secret-key: 6LfdZU0mAAAAAMzjZMZNpik_071rjNU4Gpni8F0R
    verify-url: https://www.google.com/recaptcha/api/siteverify
    site: 6LfdZU0mAAAAALkr5VZvS0s5h1db-9suCbyRoOLC
    score-threshold: 0.5

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.12:5432/market
    username: market_owner
    password: market_owner
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
            clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 121189305185277
            clientSecret: 42ffe5aa7379e8326387e0fe16f34132
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: d3e47fc2ddd966fa4352
            clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
